### PR TITLE
added blog post about new automated releases updates

### PR DESCRIPTION
**Pull request by Graur**
## PR-Codex overview
This PR automates the process of pulling new releases for EO libraries, saving developers time and ensuring the codebase is always up-to-date. 

### Detailed summary
- Adds a new post to the `_posts` directory with information on the automated pull system for new releases of EO libraries
- Describes the manual process of creating a pull request for new releases and the benefits of automating it
- Outlines the steps of the automated pull system, which runs once an hour every day to check for new releases of Objectionary libraries and creates a new pull request with corresponding changes if a new release is found

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 I added a new blog post about automated releases updates in our Home repository. Can you please give some feedback?

**Comment by yegor256** [comment]
@Graur it seems that a more detailed introduction to the problem is required. Now, the article assumes that the reader understands what is a "release", where they are coming from,  where we put them, etc. It would be great if we first spend a few paragraphs to introduce our architecture, explain the problem (packages need to be manually put into objectionary/home) and only then show the solution.

**Comment by Graur** [comment]
@yegor256 I've added short description of the release process. Could you please give some feedback one more time?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
