### PR TITLE
error and try objects

### PR DESCRIPTION
**Pull request by Graur**

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by Graur** [comment]
Screenshot 2022-07-18 at 15 55 10

**Comment by yegor256** [comment]
@Graur I think it's better to merge this blog post with #10

**Comment by yegor256** [comment]
@Graur yes, exactly. I think these two topics are tightly related to each other.

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@Graur there are a few grammar mistakes, please re-read it again. Also, make sure you indent the code right. Now one snippet is too far right.

**Comment by Graur** [comment]
@yegor256 My bad, I fixed them. Could you please check again?

**Comment by yegor256** [comment]
@Graur thanks!

**Pull request merged**
