### PR TITLE
New post: placed catalog

### PR DESCRIPTION
**Pull request by mximp**
New post: placed catalog

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by mximp** [comment]
@yegor256 reminder

**Comment by mximp** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@mximp see the changes I made in f3f02e3. It's better to avoid italic and bold fonts in the text, unless you **really** need to shout out loud something. In this case, you don't shout, you just need to make a difference between the main text and some embedded code samples.

**Comment by mximp** [comment]
> @mximp see the changes I made in [f3f02e3](https://github.com/objectionary/news.eolang.org/commit/f3f02e3d255af6bd0a22bb7422c6abd8795b2a2e). It's better to avoid italic and bold fonts in the text, unless you **really** need to shout out loud something. In this case, you don't shout, you just need to make a difference between the main text and some embedded code samples.

@yegor256 thank you. I will take this into account. Indeed I just wanted to make some terms different.

**Pull request merged**
